### ISSUE TITLE
Missing search results

### ISSUE THREAD

**Issue by theDanielJLewis** [drawrowfly/amazon-scraper#109]
I'm running into a weird issue where Amazon Buddy is not finding things it should.

For example, [this web search currently returns 5 results](https://www.amazon.com/s?k=The+Audacity+to+Podcast&i=audible), including a podcast called "The Audacity to Podcast."

But run the search with Amazon Buddy and it hangs:

```sh
amazon-buddy products -k "The Audacity to Podcast" --category audible
⠦ Amazon Scraper StartedError: No more products
    at AmazonScraper.grabProduct (/Users/…/.nvm/versions/node/v16.19.1/lib/node_modules/amazon-buddy/lib/Amazon.js:1338:19)
    at /Users/…/.nvm/versions/node/v16.19.1/lib/node_modules/amazon-buddy/lib/Amazon.js:277:30
⠏ Found 27 products
```

If I remove the category filter, it saves the results to a file, but the results do _not_ contain the specific product I'm expecting (ASIN `B08K58D27V` in the USA).

Using the module inside Node.js, I get 0 results when filtering with the "audible" category.

This same kind of process works fine for other podcasts, for example:

```sh
amazon-buddy products -k "Morbid" --category "audible"
```

And then the expected result (ASIN `B08JJTBBH6` in the USA) is included—#1, actually.

So it seems like the search is somehow glitching, but also not even returning the expected results.

**Comment by EliaTolin** [comment]
Hello have you fix it? @theDanielJLewis

**Comment by theDanielJLewis** [comment]
@EliaTolin, no. I never found a fix. At this point, it looks like this project has been abandoned since it's been almost three years since an update.
